### PR TITLE
Addition of seeq-plot-curve into the gallery

### PR DESCRIPTION
**Pull request by Flaminator89**

### CODE REVIEW

**Comment by anvenkat18** [comment]
@Flaminator89 Is there associated documentation? Please look at MPS or Correlation for an example.

**Comment by anvenkat18** [comment]
The image may need to be resized to be similar to others (seems to be too large at the moment)

**Comment by Flaminator89** [comment]
Good catch - I've resized it now.  I don't have any documentation for it right now, but will be add that.

**Comment by anvenkat18** [comment]
Great @Flaminator89 . Lets get the documentation in place before adding to the gallery.

**Comment by Flaminator89** [comment]
> Great @Flaminator89 . Lets get the documentation in place before adding to the gallery.

You bet - revised with the documentation link.  Thanks!

**Pull request merged**
